### ISSUE TITLE
Class 'Symfony\Component\EventDispatcher\Event' not found

### ISSUE THREAD

**Issue by IftekherSunny** [thephpleague/oauth1-client#103]
Hey, 

Event class not found when I'm using oauth1-client with my laravel project.

- laravel version: 7.*
- Symfony event dispatcher: 5.*

I was trying to install 4.* version of event dispatcher. But it created conflict with laravel project.

So do oauth1-client only works with event dispatcher 5?

**Comment by kasparasg** [comment]
I've seen this issue as well the other day. Happy to make a contribution if someone gave pointers on how to go about this 🤔

**Comment by kasparasg** [comment]
Looks like this change fixes the problem https://github.com/thephpleague/oauth1-client/pull/101

**Comment by bencorlett** [comment]
This should be resolved in 1.8.0 :)
