### ISSUE TITLE
Options for authorization URL

### ISSUE THREAD

**Issue by patrickkusebauch** [thephpleague/oauth1-client#130]
In the same vein as the [OAuth2 client](https://github.com/thephpleague/oauth2-client/blob/419d163a02654305773e07731dc26ce7528a574f/src/Provider/AbstractProvider.php#L386) the OAuth1 client should allow for additional options when constructing the Authorization Url. As per [OAuth 1 RFC 5849](https://tools.ietf.org/html/rfc5849#page-11):

> Servers MAY specify additional parameters.

A second parameter for `$options` that would merge with the token from temp credentials would be ideal IMHO.

**Comment by bencorlett** [comment]
This functionality exists within V2 which I’m working through documenting in my spare time :)

I’m not planning on adding any new functionality to the existing version except security patches at this stage :)

**Comment by patrickkusebauch** [comment]
@bencorlett The latest released stable version is v1.8.2, and in that version, it is not present. Hence from a consumer's standpoint, it does not exist. What is necessary for v2 to be released?

**Comment by bencorlett** [comment]
Once I have finished up documenting V2, it’ll be released :) see the gh-pages branch. 

Just finding the spare time to invest in this. 

I welcome a PR if you want to add this to v1.
