### ISSUE TITLE
Avoid "functions" from dependencies

### ISSUE THREAD

**Issue by marcorocca** [thephpleague/oauth1-client#134]
Guzzle has deprecated the use of functions provided by their dependencies (as you can see [here](https://github.com/guzzle/guzzle/pull/2712)) in their latest versions.
I think it might make sense to upgrade the use of them in `oauth1-client` too, for example in `EncodesUrl.php`:
```
protected function createUrl($uri)
{
    return Psr7\uri_for($uri);
}
```
Becomes:
```
protected function createUrl($uri)
{
    return Psr7\Utils::uriFor($uri);
}
```
This will make the library future proof of any deprecation (and eventually give us the ability to use [Mozart](https://github.com/coenjacobs/mozart) on it, as at the moment it will crash on those function calls).

**Comment by smares** [comment]
The library is now broken with the release of guzzlehttp/psr7 2.0 which itself is a dependency of guzzlehttp/guzzle 1.7.

**Comment by bencorlett** [comment]
I will prioritise fixing this. I might as well release 2.0 as well, I’ve been using it for months now :)

**Comment by bencorlett** [comment]
I have created #135 to address this. @smares did you want to cast your eye over this?
