### ISSUE TITLE
[Proposal] Add UserVoice Server

### ISSUE THREAD

**Issue by assertchris** [thephpleague/oauth1-client#19]
Hi friends,

I recently created a UserVoice Server class, and was wondering if you'd like me to push it upstream?

**Comment by stevenmaguire** [comment]
Submit a PR and let's take a look!

**Comment by bencorlett** [comment]
Absolutely :)

Sent from my iPhone

Please excuse my brevity

**Comment by assertchris** [comment]
You got it!

**Comment by stevenmaguire** [comment]
@assertchris Can we close this issue?

**Comment by assertchris** [comment]
I guess so. Was planning to do so after I'd submitted the PR...

**Comment by stevenmaguire** [comment]
Yay @assertchris!
