### ISSUE TITLE
Custom Server Class

### ISSUE THREAD

**Issue by DraperStudio** [thephpleague/oauth1-client#62]
I need to have a custom `Server` class because I need to overwrite the `getTokenCredentials` permanently for everything that would extend my `Server`.

Now the issue is that I need to extend the existing `League\OAuth1\Client\Server\Server` which has tons of abstract methods that need to be implemented which results in the following `Server` class for me.

```php
<?php

use League\OAuth1\Client\Credentials\TemporaryCredentials;
use League\OAuth1\Client\Credentials\TokenCredentials;

class Server extends \League\OAuth1\Client\Server\Server
{
    public function getTokenCredentials(TemporaryCredentials $temporaryCredentials, $temporaryIdentifier, $verifier)
    {
        // my new getTokenCredentials-method
    }

    public function urlTemporaryCredentials()
    {
        //
    }

    public function urlAuthorization()
    {
        //
    }

    public function urlTokenCredentials()
    {
        //
    }

    public function urlUserDetails()
    {
        //
    }

    public function userDetails($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    public function userUid($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    public function userEmail($data, TokenCredentials $tokenCredentials)
    {
        //
    }

    public function userScreenName($data, TokenCredentials $tokenCredentials)
    {
        //
    }
}
```

So what would be your advice on how to build my custom `Server` class without having this bunch of empty methods?

**Comment by stevenmaguire** [comment]
You will need to implement each of those methods for this class to function properly. Otherwise, you will need to find one of the existing provider specific implementations to use as your base class then override the single method you are interested in at this time.

**Comment by DraperStudio** [comment]
Well the thing is I need to override the `getTokenCredentials `-method completely and my `Server` class should replace the `League\OAuth1\Client\Server\Server`.

My Providers would then extend `MyNamespace\OAuth1\Server` instead of `League\OAuth1\Client\Server\Server`.

So how do I replace the League Server with my own Server class?

**Comment by stevenmaguire** [comment]
Can you describe your use case here a bit more? How many provider specific implementations are you planning to build? Do they share some logic and behavior? If so, what?

**Comment by DraperStudio** [comment]
This would be used for all the OAuth1 Providers at https://github.com/SocialiteProviders. All OAuth1 Providers look pretty much like this.

**Twitter/Provider.php**
```php
<?php

namespace SocialiteProviders\Twitter;

use League\OAuth1\Client\Credentials\CredentialsException;
use SocialiteProviders\Manager\OAuth1\User;

class Provider extends TwitterAbstractProvider
{
    /**
     * Unique Provider Identifier.
     */
    const PROVIDER_IDENTIFIER = 'TWITTER';

    /**
     * {@inheritdoc}
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user['extra'])->map(
            [
                'id' => $user['id'],
                'nickname' => $user['nickname'],
                'name' => $user['name'],
                'email' => $user['email'],
                'avatar' => $user['avatar'],
            ]
        );
    }
}
```

-----

I need the custom Server class because I need to grab the response received after requesting the access token.

**Comment by bencorlett** [comment]
Hi @DraperStudio, I am trying to understand the issue here.

As I understand it, your problem is that you have a bunch of empty methods in your implementations?

If so, there's really not much we can do about that in v1 as this would seriously break BC. In V2 this has been refactored and it might just be worth waiting out for this.

**Comment by bencorlett** [comment]
As far as replacing the League's server class, I'm not sure if I'm missing what you're asking here as well. I don't believe anything else would be required other than you extending that class in your own custom implementation (for the `getTokenCredentials()` method you described).

Going to close off the issue now, feel free to reopen if you need further clarification or I've missed what you're asking :)
