### ISSUE TITLE
Tumblr does not accept oauth_signature when trying to get access token

### ISSUE THREAD

**Issue by JaffParker** [thephpleague/oauth1-client#64]
Signature of the request passes fine when I'm getting the OAuth token, but it fails when I try to get the access token. The error that I get from Tumblr is this:

> oauth_signature does not match expected value

I tried to Google the error, but the only reasons I found were typos. I verified that I didn't make a mistake, but the error is still there. I appreciate your help!

**Comment by bencorlett** [comment]
Heya, are you able to clarify what you're doing with a code sample?

**Comment by JaffParker** [comment]
Sure. To clarify: I'm using Laravel Socialite, which uses League's OAuth1 Client, so here's the code:

```PHP
    public function user()
    {
        if (! $this->hasNecessaryVerifier()) {
            throw new InvalidArgumentException('Invalid request. Missing OAuth verifier.');
        }

        $user = $this->server->getUserDetails($token = $this->getToken());
        dd($user);
    }
```

Then `getToken()` looks like this:

```PHP
    protected function getToken()
    {
        $temp = $this->request->getSession()->get('oauth.temp');

        return $this->server->getTokenCredentials(
            $temp, $this->request->get('oauth_token'), $this->request->get('oauth_verifier')
        );
    }
```

And `$this->server` is an instance of `League\OAuth1\Client\Server\Tumblr` class.

**Comment by bencorlett** [comment]
Are the values of:

```php
$temp,
$this->request->get('oauth_token'),
$this->request->get('oauth_verifier')
```

All correct?

Obviously it's not easy to know if they're "correct", but do they look suspicious or are any empty?

**Comment by JaffParker** [comment]
You sir, are a genius. `oauth.temp` did not have the secret, it was removed at some step. Pretty stupid error, but thank you for guiding me :)

**Comment by bencorlett** [comment]
You’re most welcome :)
