### ISSUE TITLE
The package is using the deprecated guzzle/guzzle instead of guzzlehttp/guzzle

### ISSUE THREAD

**Issue by j3j5** [thephpleague/oauth1-client#72]
This package requires on composer.json `guzzle/guzzle` on its version 3 which is deprecated in favor of `guzzlehttp/guzzle`. 

The latest maintained version is `guzzlehttp/guzzle` 5.x, which has a new namespace. I can create a PR if you are fine with it.

**Comment by bencorlett** [comment]
Hey @j3j5, I just saw your comment on #71, good to know somebody else is running that code without issue as well :)

I'm going to close this off now.
