### ISSUE TITLE
New Tag would be nice

### ISSUE THREAD

**Issue by Jacco-V** [thephpleague/oauth1-client#76]
Hi,

Since the last Tag (1.6.1) is from 23 Oct 2015, it would be really nice if you guys could Tag a new version, so that the various fixes and improvements would be available to the wider audience.

**Comment by bencorlett** [comment]
Hey @Jacco-V, this is extremely good feedback actually. I am ashamed it's been that long!

We have tagged `1.6.1` with all bug fixes up until now, and `1.7.0` which moves away from the depreciated `guzzle/guzzle` package and are supporting the latest version :)

See #71 and #75
