### ISSUE TITLE
Salesforce integration

### ISSUE THREAD

**Issue by RobinBarnwell** [thephpleague/oauth1-client#90]
Hello

Will this allow me to create an OAuth connection to Salesforce?  I want to send two REST calls from Wordpress:

1.  When a new user is created, REST PUT to create a contact in Salesforce, updating the Wordpress user with the Salesforce ID generated

2. When the user profile is updated, REST PATCH to update the contact in Salesforce using the ID

This would be fantastic, would be happy to donate if this can be made to work.

Robin

**Comment by stevenmaguire** [comment]
Salesforce uses OAuth2. This package is for OAuth1. There is a package for Salesforce OAuth2. 

https://github.com/stevenmaguire/oauth2-salesforce
